# Don't touch this!
config-version: 1

# If true, when drinking milk the cigarette will be extinguished.
remove-when-drinking-milk: true

# Default sounds, used when a custom cigarette doesn't have custom sounds.
sounds:
  light: "ITEM_FLINTANDSTEEL_USE, 1.0, 1.0"
  extinguish: "BLOCK_LAVA_EXTINGUISH, 1.0, 1.0"
  smoke: "BLOCK_FIRE_AMBIENT, 1.0, 1.0"

messages:
  not-from-console: "&cThis command can't be used from the console!"
  no-permission: "&cYou don't have permission to execute this command."
  player-not-found: "&cPlayer not found!"
  requires-lightning: "&cThis cigarette must be lit with a flint and steel or a fire charge!"
  usage: "&aUsage: /cigarette reload or /cigarette give [name] <player>"
  reloading: "&aThe plugin is being reloaded in another thread, wait a few seconds..."
  reload: "&aPlugin reloaded!"
  unknown: "&cThat cigarette doesn't exists."
  extinguish: "&aYour cigarette is over."
  light: "&aCiggy lighted!"