name: Cigarette
version: ${project.version}
main: me.matsubara.cigarette.CigarettePlugin
api-version: 1.17
author: Matsubara
description: ${project.description}

commands:
  cigarette:
    usage: /<command>
    description: main command.